=== CASHCART/WT/Set-06-Q1 - Book XML DTD/books.dtd
<!ELEMENT library (book+)>
<!ELEMENT book (title,author,ISBN,publisher,edition,price)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT edition (#PCDATA)>
<!ELEMENT price (#PCDATA)>

=== CASHCART/WT/Set-06-Q1 - Book XML DTD/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE library SYSTEM "books.dtd">
<library>
  <book>
    <title>Learning XML</title><author>John Doe</author><ISBN>978-1-23456-789-0</ISBN>
    <publisher>Tech Press</publisher><edition>2nd</edition><price>499.00</price>
  </book>
  <book>
    <title>Advanced Javascript</title><author>Jane Smith</author><ISBN>978-0-98765-432-1</ISBN>
    <publisher>Code World</publisher><edition>1st</edition><price>799.00</price>
  </book>
</library>
